### ISSUE TITLE
Lint Issue - Invalid Line Break

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#10]
I am unsure what to change the line brake seems the same as it as with achievement

![error](https://cloud.githubusercontent.com/assets/2480828/10739827/02719be8-7bdc-11e5-9bc6-55104cf16f65.PNG)

[factory.txt](https://github.com/gios-asu/sustainability-game/files/21174/factory.txt) Saved as text so you can see what i have in the file. as it wont let me add js here.

"/**
- A Factory
  */
  var Factory = function( options ) {
  options = options || {};
  this.name = options.name;
  };

module.exports = Factory;
"

**Comment by idmontie** [comment]
Are you sure the line ending are UNIX (LF)? If you are in Sublime, you can open up the sublime preferences file to open up the workspace with Unix line ending set.

**Comment by msdickinson** [comment]
I was using notepad++, Although i checked if its correct there. its likey not.
Ill try web-storm or sublime.

**Comment by idmontie** [comment]
Notepad++ will usually not convert line endings, but it by default will use LFRF on Windows. You can have Notepad++ display line endings (they will appear in black pills at the end of each line). It's better to just use an editor that will automatically convert them for you, though.

**Comment by msdickinson** [comment]
Works. Thanks. Using Web Storm.
