### ISSUE TITLE
MainSideBar 

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#109]
Hi, Ivan:
Which one is the MainSideBar?
<img width="258" alt="16843340-7bf7-49c3-8ec9-14d499fff9fb 2" src="https://cloud.githubusercontent.com/assets/6620363/13581362/c5b6063a-e463-11e5-9503-c864cb8f757b.png">
<img width="291" alt="e2d89891-f99c-4b47-8a46-482992174535" src="https://cloud.githubusercontent.com/assets/6620363/13581383/e07e5120-e463-11e5-8422-3bdbec01b036.png">
Do we expect to finish all our tasks on Asana by Thursday? Or only these tasks we are assigned to?

**Comment by idmontie** [comment]
The side bar is the entire left side of the screen. Finish what you can by Thursday.

**Comment by xyan12345** [comment]
so this is the MainSideBar, combine each small components. Right?
<img width="257" alt="1d106bf1-9b95-45d4-8bf7-a69288a08885" src="https://cloud.githubusercontent.com/assets/6620363/13581737/98e63362-e465-11e5-9443-ab0b3d06fc1a.png">
Thanks!

**Comment by idmontie** [comment]
Yup, that's correct.

**Comment by xyan12345** [comment]
Thanks!
