### ISSUE TITLE
Lint Issue

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#111]
Cant Figure out what it means Expected property shorthand 

  25:43  error  Expected property shorthand  object-shorthand

![lint issue](https://cloud.githubusercontent.com/assets/2480828/13678984/bd533fa6-e6ae-11e5-8693-5b76d66e3db5.PNG)
![lint issue 2](https://cloud.githubusercontent.com/assets/2480828/13678986/bec131c2-e6ae-11e5-83f8-094c179947fc.PNG)

**Comment by msdickinson** [comment]
Looks like it works fine, if i change programName: programName -> abc: programName

**Comment by idmontie** [comment]
Short hand notation is:

```
() => { }
```

or if you are within a class:

```
class xyz {
  myMethod() {
  }
}
```

**Comment by rraub** [comment]
FYI try googling the lint error -> http://eslint.org/docs/rules/object-shorthand
