### ISSUE TITLE
MainActionAreaWindow (Task)

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#113]
One of my asks are "MainActionAreaWindow"

I assume this is the area its talking about

![isthismainactionarea](https://cloud.githubusercontent.com/assets/2480828/13679541/78689c58-e6b1-11e5-8180-f18c720939f4.PNG)

If so the code is telling me its already. done.

![thisimage](https://cloud.githubusercontent.com/assets/2480828/13679675/44403cc8-e6b2-11e5-8225-5b70ed232758.PNG)

**Comment by msdickinson** [comment]
maybe your refering to the box, things to do?

**Comment by msdickinson** [comment]
I am gonna consider this done.

**Comment by idmontie** [comment]
No.

**Comment by idmontie** [comment]
The part under it is the MainActionAreaWindow.

**Comment by msdickinson** [comment]
Hmm. you refering too the box that has the list in it. but not the list?

**Comment by msdickinson** [comment]
where it says "Things to do"?

**Comment by idmontie** [comment]
Yeah, that whole area around that. It needs to be containered by something, especially if we ever add those tabs that we planned back in (which we probably won't get to).
