### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by Tuyenho** [asu-ke-web-services/dont-get-fired-game#118]
Is there anyway to write test cases for EventPage variables, so i changed 
export default.... to const EventPage...export { EventPage }
this is the code i changed. 
![11](https://cloud.githubusercontent.com/assets/8674207/13721279/3219fcb4-e7de-11e5-9630-57853b6ef88e.JPG)

![12](https://cloud.githubusercontent.com/assets/8674207/13721280/37c55b4a-e7de-11e5-9f76-c1d667f674ac.JPG)

this is the error i got when i run : npm run testonly 
![10](https://cloud.githubusercontent.com/assets/8674207/13721282/44ac4774-e7de-11e5-8023-1ff31dbddbef.JPG)

**Comment by rraub** [comment]
In your test you'll want to change your import statement
`import { EventPage } from '../event-page.jsx';`
and you will want to pass the specific property value along rather than the whole event object.

**Comment by Tuyenho** [comment]
thank you this helps alot
