### ISSUE TITLE
We are in need of guidance

### ISSUE THREAD

**Issue by drsmall** [asu-ke-web-services/dont-get-fired-game#124]
We are at a very close state to having the front end done. We've been working on a new branch called WeekendPUSH. We fixed all of the issues Ivan pointed out and it appears to be in a working state.

We have been reviewing  
   let game = new Game();
   game.init();

There is a lot going on. It appears Ivan did most of the back end, and just wanted us to finish the back-end and connect it to the front end, in the reducer. 

We have reviewed this for the last few hours. and come up to the conclusion that we are unable to understand it well enough, to use it in the project with out further guidance.

If we are unable to figure his code out, we may come up with an alternative back-end, for the project. More or less doing it from scratch.and it would meet all the primary objectives of this project. A much more simple back-end.

However, it seems to be much faster if we get some help or guidance on this in the next day or 2 to get us going in the right direction and get as much done before we meet this Thursday.

**Comment by msdickinson** [comment]
+1

For Example: we dont see where in game, it is holding all the programs.

**Comment by Tuyenho** [comment]
+1

**Comment by xyan12345** [comment]
+1

**Comment by rraub** [comment]
Sorry I didn't reply sooner. The game model currently doesn't have everything, Ivan just setup some of the state to get things going. I would imagine that the simplest approach for adding in the programs would be to just create a new class attribute for the Game model with the programs. Which can be loaded directly from the program data or filtered through a new program builder (that hasn't been written yet) that could randomly pick or alter the program data to add some other attributes (like is_purchased) to keep track of the game state.

You will also need to add a function to purchase a program, that can most likely go in the game model to enforce the prerequisite requirements.  That function would get called from the reducer when the purchase program action is dispatched. 

Do you have any other specific questions? Its hard to answer the broad "I don't understand" without specifics.

**Comment by msdickinson** [comment]
Can we pick and choose what parts of the back end to use? or do we have to use all of it and try to integrate  the programs in with it. I have reviewed the files many times, and dont truly grasp how to make that work.

On the other hand, If we use what makes sense to us and drop the parts that dont, and hit all requirements using additional code we fully understand. Is that ok?

In other words. Is it required we use hes backend. Or  if we can meet the requirements can we use our own, and just use what we want from hes.?

**Comment by msdickinson** [comment]
" I would imagine that the simplest approach for adding in the programs would be to just create a new class attribute for the Game model with the programs. "

This much we understood. We did not understand how our new class would intergrate wiht the existing system.

Take for example company.js

" addFactory() {
    // Special case of a program purchase
    // TODO descrease cash
    // TODO add a factory
  }

  removeFactory() {
    // TODO remove a factory
  }"

Whats a factory? we dont have factorys.

"    // TODO calculate waste" Waste? there seems to be alot more involed in ivens back end. then.
add a factory, then, somthing that makes a simple effect on the user

" let productionCap = this.productionCapRule.calculate(
        this.industry.potentialSalesPerQuarter,
        this.marketPenetration,
        this.averageFactoryEfficiency,
        this.numberOfFactories,
        this.industry.maximumOutputPerFactory
    );
    let sales = this.salesRule.calculate(
        this.marketPenetration,
        this.industry.getCalculatedMetrics().marketSizeInDollars,
        this.industry.maximumOutputPerFactory,
        this.averageFactoryEfficiency,
        this.numberOfFactories
    );
    let costs = this.costsRule.calculate(
        this.industry.quarterCostPerFactory,
        this.numberOfFactories,
        this.averageFactoryEfficiency,
        this.materialCostsRule.calculate(
            this.industry.materialCostsPerSale,
            productionCap
        ),
        this.programCosts
    );"

This again, does this involve the programs?

I will post what I had in mind, to see what you think.

"can be loaded directly from the program data or filtered through a new program builder (that hasn't been written yet) that could randomly pick or alter the program data to add some other attributes (like is_purchased) to keep track of the game state."

This we under stood.

"You will also need to add a function to purchase a program, that can most likely go in the game model to enforce the prerequisite requirements. That function would get called from the reducer when the purchase program action is dispatched."

We also under stood this.

**Comment by rraub** [comment]
I think if you pick and choose parts of the backend to use, you will end up with something thats much harder to get working. That being said a working prototype is the desired deliverable so cutting some corners is reasonable.

There is a fair amount of legacy code still in the repo from the first iteration of the game, so that might be adding to your confusion. Waste and Factories have been removed from this revision of the game in favor of the programs. 

I would suggest for you to add one feature at a time, get it working and in the game then add to it. So just focus on getting programs into the game state, then display them, then make them purchasable, then make them actually effect the other aspects of the game state. Trying to do everything all at once is allot to keep track of.

**Comment by msdickinson** [comment]
Sounds good.
