### ISSUE TITLE
React Issue? Or Do I am Missing somthing...Maybe a hidden bug?

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#125]
import React from 'react';
import { default as NQB } from '../../game/sidebar/next-quarter-button/next-quarter-button.jsx';
// import { default as advisorPanel } from '../advisor-panel/advisor-panel.jsx';
// import { default as companyName} from '../company-name/company-name.jsx';
// <companyName/>
// <advisorPanel/>

export default React.createClass({
    render() {
        return (
            <div className="main-side-bar">
                <div className="company-name">

```
            </div>
            <div className="advisor-panel">

            </div>
            <div className="next-quarter-button">
                <NQB/>
            </div>
        </div>

    );
}
```

});

This WORKS

VS

import React from 'react';
import { default as nextQuarterButton } from '../../game/sidebar/next-quarter-button/next-quarter-button.jsx';
// import { default as advisorPanel } from '../advisor-panel/advisor-panel.jsx';
// import { default as companyName} from '../company-name/company-name.jsx';
// <companyName/>
// <advisorPanel/>

export default React.createClass({
    render() {
        return (
            <div className="main-side-bar">
                <div className="company-name">

```
            </div>
            <div className="advisor-panel">

            </div>
            <div className="next-quarter-button">
                <nextQuarterButton/>
            </div>
        </div>

    );
}
```

});

Not Work, I have even replaced nextQuarterButton With nextQuarterButtonZ (Clearly not used anywhere else in code)

import React from 'react';
import { default as nextQuarterButtonZ } from '../../game/sidebar/next-quarter-button/next-quarter-button.jsx';
// import { default as advisorPanel } from '../advisor-panel/advisor-panel.jsx';
// import { default as companyName} from '../company-name/company-name.jsx';
// <companyName/>
// <advisorPanel/>

export default React.createClass({
    render() {
        return (
            <div className="main-side-bar">
                <div className="company-name">

```
            </div>
            <div className="advisor-panel">

            </div>
            <div className="next-quarter-button">
                <nextQuarterButtonZ/>
            </div>
        </div>

    );
}
```

});

Also Not work. something fishy is going on. Any Clue? If not Ill use Short all cap var names for things that work with what that they should be called...

**Comment by msdickinson** [comment]
NQAX works, NQAXX Works. So... no idea whats going on.

**Comment by rraub** [comment]
React Components should start with a capital letter and be title case. I think that is the issue you are running into.

**Comment by rraub** [comment]
https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components
