### ISSUE TITLE
Made Major Changes To Weekend Branch...

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#127]
Its a long ways off. And we will be able to reuse alot of what Ivan had in has, or at least hes concepts on most of hes classes.

To make sure I didn't get mixed up I named all the files CS...

But game is starting to become functional.
By Thursday I suspect It will be at a fully functional state, with just no random data sets.
(With Strong Team Effort, Tomorrow, and Wednesday night)

Let me know if you have a chance to run, the game on this, and if you think i am going in the wrong direction. But this makes the most sense to me.

**Comment by msdickinson** [comment]
Note the pull request that's up now is the weekend version before adding these new files

**Comment by rraub** [comment]
Its looking good! your making some good progress and I hope your finding out that this framework isn't as tricky as you initially thought. 

The CS prefix is fine for now if it helps keep things straight.
