### ISSUE TITLE
Coverage Error Preventing Project Build

### ISSUE THREAD

**Issue by drsmall** [asu-ke-web-services/dont-get-fired-game#13]
I still have this error
![image](https://cloud.githubusercontent.com/assets/8838369/10743330/9d6885e0-7bef-11e5-9de6-9a074566e470.png)

@rover2341 , were you able to 'gulp' and build the project successfully?

**Comment by msdickinson** [comment]
Yes

**Comment by idmontie** [comment]
It looks like coveralls is unable to create the debug directory. You can resolve this for now by disabling coveralls in your gulp file.

**Comment by drsmall** [comment]
Issue fixed by adding 'debug' folder to the root of the project.
