### ISSUE TITLE
It claims I am not using, game but I am. and its required for the test. Is there a suppression for this?

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#137]
``` js
import React from 'react';
import {expect} from 'chai';
const {describe, it} = global;
import {render} from 'enzyme';
import { default as AdvisorPanel } from '../advisor-panel.jsx';

describe('Advisor Panel', () => {

  var gameData = { game: {
    advisors: [
      {
        name: 'Ivan',
        advice(game) {
          sentiment = {
            statement: 'Customers are saying they love your company!',
            feeling: 'GOOD',
          };
          return sentiment;
        }
      }
    ],
    goals:
      {
        captial: 50,
        satisfaction: 100
      },

    totalSatisfaction: 50,
    totalCapital: 50,
    totalQuarters: 15,
    actionsPerQuarter: 5
  }
  };

  it( 'has one advisor', () => {
    const wrapper = render(<AdvisorPanel game={gameData} />);
    expect(wrapper.contains('Ivan')).to.equal(true);
  });
});
```

**Comment by msdickinson** [comment]
Note this is on BetaThree commeted out at the moment. if you want to look at most recent code.

**Comment by imontiel** [comment]
Do you mean in this section:

```
advice(game) {
  sentiment = {
    statement: 'Customers are saying they love your company!',
    feeling: 'GOOD',
  };
  return sentiment;
}
```

is throwing a lint error because `game` is not used? You can just remove `game` from the parameters: `advice() {`

**Comment by idmontie** [comment]
Do you mean in this section:

```
advice(game) {
  sentiment = {
    statement: 'Customers are saying they love your company!',
    feeling: 'GOOD',
  };
  return sentiment;
}
```

is throwing a lint error because `game` is not used? You can just remove `game` from the parameters: `advice() {`

**Comment by msdickinson** [comment]
I dont believe i can

https://github.com/gios-asu/dont-get-fired-game/blob/develop/client/components/game/advisor-panel/advisor-panel.jsx

I am using game.advisors on the other page. and i need game, to make the function work.'

Prehaps if i ran "advisor.advice(this.props.state.game);" before it got to advisor-panel.jsx 

I didnt do it that way, cause i thought if i added more to the reducer, for that page. that the old state would get pushed around to all the other pages. that is not needed...

case ACTION_ENUM.SHOW_MAIN:
      return {
        ...oldState,
        scene: SCENE_ENUM.MAIN_SCENE
      };

If I were to run it when ever I go to main_scene (more then 1 spot)

I figured the way its setup at the moment is fine. If not then If i pass in the data though the reducer, then, I would have to strip it out on the next state. cause oldState would continue to hold that data. that just seemed like a worse solution to me. (unless i am confused, most likey the case)

**Comment by rraub** [comment]
for your test data you could throw in a meaningless statement that uses `game` just to get around this problem. 

``` js
advice(game) {
  if(game) {
    sentiment = {
      statement: 'Customers are saying they love your company!',
      feeling: 'GOOD',
    };
  }
  return sentiment;
}
```

**Comment by msdickinson** [comment]
I was doing my code wrong. It was looking for state, not game. Fixed.
