### ISSUE TITLE
FYI chrome Plugin for React Developer Tools

### ISSUE THREAD

**Issue by rraub** [asu-ke-web-services/dont-get-fired-game#148]
If you didn't know about this already it's really handy:
https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?utm_source=gmail

<img width="1174" alt="screen shot 2016-04-06 at 9 42 29 am" src="https://cloud.githubusercontent.com/assets/295804/14324936/e87cb1de-fbdb-11e5-833e-a861a13c890f.png">

ping @rover2341 @xyan12345 @Tuyenho @drsmall @ramorga

**Comment by msdickinson** [comment]
Neat, I installed the plugin, but never saw the react at the top. was still useful. but with this its more useful.

+1
