### ISSUE TITLE
Line Endings 

### ISSUE THREAD

**Issue by drsmall** [asu-ke-web-services/dont-get-fired-game#149]
I've gotten over 2000 errors about lineendings supposed to be LF, but they are CRLF when I run lint. It is strange because the errors are coming from files I didn't touch. I'll try to fix this tonight and tomorrow morning. Any guidance would be appreciated.

**Comment by msdickinson** [comment]
Ya no idea, I just pulled from latest, and made a bunch of changes over the last few hours and didn't have that issue. I can only assume isolated Issue. Anyway No idea.

(My guess is a setting in web storm) There may be a way to tell all files in webstorm to use LF. 
Sounds sorta like webstorm decided to change all files to CRLF. But it may not be related to that only my best guess.

**Comment by rraub** [comment]
Most likely it is an editor setting, especially when you have files coming from windows and linux/osx its easy for things to get converted.
