### ISSUE TITLE
Anything Else? Aside From Style + Game Balance

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#151]
Please Run the game on the latest pull Request when you get a few min.
Just play it once or twice.

I want to make sure there is nothing left that is expected on the project.

I know David will get the UI.
And the other 3 can Improve the game balance some more.

Is there anything else you would like us to do on this project?
I am think i got everything we talked about.

**Comment by rraub** [comment]
The only other thing that I can think of is presenting the costs for the programs in the list of programs so you can compare the programs easier. 

Also theres no tweeting #154 

Other than that I think its good to go

**Comment by msdickinson** [comment]
My Version is different then Davids. But Will change showing program cost as well.
(Most fixs and changes are not on davids, just style on davids)

**Comment by msdickinson** [comment]
"presenting the costs for the programs in the list of program." I did this on my home build, but I thought it looked bad. (Just now)

If you think we need it anyway ill add. for now i have not committed on my home machine, as I assume ill revert.

Please advice.

**Comment by rraub** [comment]
I think its useful information thats necessary for comparing programs. If its ugly to display, then thats a different issue to address. I think of it like this: if Amazon didn't show prices in the product search page it would be really annoying to compare products to make a decision which one to buy.

**Comment by msdickinson** [comment]
Will Update.
