### ISSUE TITLE
"Looks like the Satisfaction goal is not getting set, its always 0"

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#155]
This is working correctly (the one you pulled in last)

But Some of the goals require zero.

![2](https://cloud.githubusercontent.com/assets/2480828/14447379/f551b936-0013-11e6-9d19-6b993fb8e7b3.PNG)
![3](https://cloud.githubusercontent.com/assets/2480828/14447377/f54daac6-0013-11e6-98cb-183f02605bd7.PNG)
![1](https://cloud.githubusercontent.com/assets/2480828/14447378/f54e0750-0013-11e6-90fb-3c4d48bcf30b.PNG)

**Comment by rraub** [comment]
so then its a wording issue, to me if the goal is 0 and i'm at 23 I've won. I think what we intend to show is there is no goal for satisfaction.

**Comment by msdickinson** [comment]
They have to meet both goals.
But can state that. if its not clear enough.

**Comment by msdickinson** [comment]
Goals:
Minimum cap:
Minimum sat:
