### ISSUE TITLE
We need Feed Back From you on this form. By Today

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#159]
[Sponsor feedback.pdf](https://github.com/gios-asu/dont-get-fired-game/files/241178/Sponsor.feedback.pdf)

Please Send this to our teacher. we are group Capstone++
We should have got this to you sooner. Its due Today.

mhekmatn@asu.edu the subject should be “Capstone II Project Feedback"

Please Let us know if your able to do this or already did.

**Comment by rraub** [comment]
Done!
