### ISSUE TITLE
Cant figure out how to Create Pull Request

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#22]
I want to push my branch to the main branch.
cant seem to figure out how

**Comment by idmontie** [comment]
If you are on your own branch:

```
git push origin my-branch-name
```

Then on github, create a new pull request and select your branch:

![github-pull-request-recording](https://cloud.githubusercontent.com/assets/412382/11319362/74dc722a-9031-11e5-827c-bec6feeb8e7c.gif)

**Comment by msdickinson** [comment]
Got it, the reason that didnt show, was because i had a old pull request. I had to close that one first.
Can I merge the pull request as well? or was that for you only to do?
Tuyen and dan, and ryhs need whats in my branch to do there parts that we hope to get done before monday.

**Comment by idmontie** [comment]
Merged. Also, watch out for your C# code style. Braces should be on the opening statement.
