### ISSUE TITLE
Format the money on the UI

### ISSUE THREAD

**Issue by idmontie** [asu-ke-web-services/dont-get-fired-game#43]

**Comment by drsmall** [comment]
I added a function called formatToMoney() that adds a dollar sign and formats the number to 2 decimal places

**Comment by idmontie** [comment]
Before we move too much with this repo, we should meet and discuss the goals for this next semester.

I think that sort of code you wrote will be reusable, but there will be some things that we will not be able to reuse in the next semester due to a small change in the direction of the game.

See this [pull request](https://github.com/gios-asu/sustainability-game/pull/62) ;) I should email this out to everyone on the team as well.
