### ISSUE TITLE
Getting Setup - npm install error Msg

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#5]
I am running Windows 10.
I followed this path
1. https://git-for-windows.github.io/ -> DL -> Install  (Line Endings Middle Option When Installing) 
   ![thisoption](https://cloud.githubusercontent.com/assets/2480828/10733338/acd58f98-7bbb-11e5-8683-b08b13927d73.PNG)
2. https://nodejs.org/en/ -> DL ->  Install
3. Open Git CMD

![myinput](https://cloud.githubusercontent.com/assets/2480828/10733483/45521d68-7bbc-11e5-8333-138f6c95c1c7.PNG)
1. npm install -g gulp
2. npm install -g browserify
3. npm install gulp

this is what it shows in my console.
![errormsg](https://cloud.githubusercontent.com/assets/2480828/10733375/c8ebf1b8-7bbb-11e5-821f-9fc8845f09fc.PNG)

[Full Console Text, all my input all the output]
[Cant Get though Install Process.txt](https://github.com/gios-asu/sustainability-game/files/20952/Cant.Get.though.Install.Process.txt)

[Checks]
- I checked that node is installed "C:\Program Files\nodejs\node.exe" It is there.

**Comment by msdickinson** [comment]
After reviewing our meeting notes I see there was guide. Step by Step. So I am now trying to follow that instead.

[9-30-2015.JavaScript.and.Git.Walkthrough.pdf](https://github.com/gios-asu/sustainability-game/files/20971/9-30-2015.JavaScript.and.Git.Walkthrough.pdf)

Step 1.
![git](https://cloud.githubusercontent.com/assets/2480828/10733688/0ffba854-7bbd-11e5-8090-eb287f5a47fa.PNG)
Permission denied (publickey). Stuck

Ah using -> http://github.com/gios-asu/sustainability-game.git Worked. For Step 1.

![http url](https://cloud.githubusercontent.com/assets/2480828/10733994/544013e6-7bbe-11e5-9e69-592924299822.PNG)

Step 2. "git checkout -b ivan-capstone-develop" I assume we type this the same or we type
   git checkout -b mark-capstone-develop both don't do anything...I must be doing it wrong somehow.

![step2nogo](https://cloud.githubusercontent.com/assets/2480828/10734132/004b26e4-7bbf-11e5-8ea3-78b69b017411.PNG)

**Comment by idmontie** [comment]
You need to `cd sustainability-game`, once in the directory, you can run the git checkout commands the npm install commands.
