### ISSUE TITLE
some errors with NPM

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#67]
I have some errors with NPM. Because of that, i am not able to run meteor.
<img width="1440" alt="screen shot 2016-02-10 at 09 27 47" src="https://cloud.githubusercontent.com/assets/6620363/12953667/a20a6c2a-cfd8-11e5-9379-5fa25dc3d4eb.png">
<img width="1440" alt="screen shot 2016-02-10 at 09 25 41" src="https://cloud.githubusercontent.com/assets/6620363/12953669/a41ec0b0-cfd8-11e5-95bc-f8862766c239.png">

**Comment by idmontie** [comment]
@rover2341  @Tuyenho   @drsmall   Has anyone else had a similar problem?

My guess is that you need to open up your NodeJS Command Line as an Administrator in order for it to be able to create folders and files.

**Comment by xyan12345** [comment]
i closed it and opened it again, it works fine now . 
<img width="1440" alt="screen shot 2016-02-10 at 09 55 08" src="https://cloud.githubusercontent.com/assets/6620363/12954810/62aec76a-cfdd-11e5-93fc-b0bbe72c403f.png">

**Comment by idmontie** [comment]
You should not be running `gulp` any more. Try `npm test`.

**Comment by idmontie** [comment]
Have you pulled down develop into your branch?

**Comment by xyan12345** [comment]
not yet, i should pull it  first and npm test, is that correct?

**Comment by idmontie** [comment]
You should definitely pull down the latest stuff from dev, re-run `npm install` and then run `npm test`.

**Comment by xyan12345** [comment]
got it, thx

**Comment by xyan12345** [comment]
Does it look right this time?
<img width="1440" alt="screen shot 2016-02-10 at 10 16 12" src="https://cloud.githubusercontent.com/assets/6620363/12955233/5dbb66b2-cfdf-11e5-9b05-84b23631c7e7.png">

**Comment by idmontie** [comment]
Yup, looks good!

**Comment by xyan12345** [comment]
Thanks
