### ISSUE TITLE
Clone to desktop permission

### ISSUE THREAD

**Issue by Tuyenho** [asu-ke-web-services/dont-get-fired-game#68]
i reinstalled my laptop and when i run command
 git clone git@github.com:gios-asu/sustainability-game.git
it said that i need permission to do so. 
![capture](https://cloud.githubusercontent.com/assets/8674207/12967855/a15b03f8-d027-11e5-99c2-d67afcefcaa0.PNG)

**Comment by idmontie** [comment]
If you are using `git@github` syntax, you will need an ssh key. Use `https://github.com...` instead.

**Comment by idmontie** [comment]
You will need to change your remote:

```
git remote origin set-url https://github.com/gios-asu/dont-get-fired-game.git
```

**Comment by Tuyenho** [comment]
its work perfectly fine thanks
