### ISSUE TITLE
Running Metor - Crash Code 8

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#69]
Steps I took:
1. I Installed Metor (https://www.meteor.com/install) Windows
2. Rebooted Windows
3. I got on branch develop
4. npm install
5. meteor

C:\Users\marks>cd capstone

C:\Users\marks\Capstone>cd sustainability-game

C:\Users\marks\Capstone\sustainability-game>meteor
[[[[[ C:\Users\marks\Capstone\sustainability-game ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20160210-18:52:42.742(-7)? (STDERR)
W20160210-18:52:42.743(-7)? (STDERR) C:\Users\marks\AppData\Local.meteor\packages\meteor-tool\1.1.11-modules.5\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160210-18:52:42.743(-7)? (STDERR)                                            throw(ex);
W20160210-18:52:42.743(-7)? (STDERR)                                                  ^
W20160210-18:52:42.743(-7)? (STDERR) Error: ENOENT, no such file or directory 'C:\Users\marks\Capstone\sustainability-game.meteor\local\build\programs\server.coverrun'
W20160210-18:52:42.743(-7)? (STDERR)     at Object.fs.openSync (fs.js:439:18)
W20160210-18:52:42.744(-7)? (STDERR)     at Object.fs.readFileSync (fs.js:290:15)
W20160210-18:52:42.744(-7)? (STDERR)     at Object.module.exports.register (C:\Users\marks\Capstone\sustainability-game\node_modules\gulp-coverage\contrib\coverage_store.js:11:33)
W20160210-18:52:42.744(-7)? (STDERR)     at __statement_fScpr2 (debug/C__Users_marks_Capstone_sustainability-game_src_core_delete-me-in-the-future.js.js:9:24)
W20160210-18:52:42.744(-7)? (STDERR)     at meteorInstall.debug.C__Users_marks_Capstone_sustainability-game_src_core_delete-me-in-the-future.js.js (debug/C__Users_marks_Capstone_sustainability-game_src_core_delete-me-in-the-future.js.js:64:5)
W20160210-18:52:42.744(-7)? (STDERR)     at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)
W20160210-18:52:42.744(-7)? (STDERR)     at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)
W20160210-18:52:42.744(-7)? (STDERR)     at C:\Users\marks\Capstone\sustainability-game.meteor\local\build\programs\server\app\app.js:4136:1
W20160210-18:52:42.744(-7)? (STDERR)     at C:\Users\marks\Capstone\sustainability-game.meteor\local\build\programs\server\boot.js:242:10
W20160210-18:52:42.745(-7)? (STDERR)     at Function._.each._.forEach (C:\Users\marks\Capstone\sustainability-game\node_modules\underscore\underscore.js:153:9)

**Comment by msdickinson** [comment]
I was suggsted to try this in node.js command prompt just in case I was running it in Git CMD. same results

**Comment by idmontie** [comment]
Did you run `npm install` from within `sustainability-game`. What is the output?

**Comment by msdickinson** [comment]
yes, It used to have an output, not it just waits for a bit and shows nothing but a new line. to continue in console.

**Comment by idmontie** [comment]
Are you sure you did not have any merge conflicts? What does `git status` show?

**Comment by idmontie** [comment]
Does this work now?
