### ISSUE TITLE
Trying to commit, Put in commit msg, but now sure how to submit

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#7]
![commit](https://cloud.githubusercontent.com/assets/2480828/10737835/a50edbe6-7bd1-11e5-8bd7-1727f28207c2.PNG)

How to press commit. return just adds a new line.

**Comment by idmontie** [comment]
If you ran `git commit`, it will open up `vim`. Typing `i` means insert. Type `:wq` to write and quit. Note the colon.
