### ISSUE TITLE
Game Start Page 

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#73]
I have problems with Game Start Page. This is how it looks like right now. 
1> How to fix the button size, and align?
2> how does react works?  Does my code look right?
Thanks
<img width="1440" alt="screen shot 2016-02-11 at 10 56 22" src="https://cloud.githubusercontent.com/assets/6620363/12985222/aa556b74-d0ae-11e5-9c5c-e3c61d80f741.png">
<img width="1440" alt="screen shot 2016-02-11 at 10 56 04" src="https://cloud.githubusercontent.com/assets/6620363/12985228/ad2a5634-d0ae-11e5-929e-79a765c11913.png">

**Comment by idmontie** [comment]
The file type should be .jsx, not .jsx.html. I will go over how to test what you react class will look like in today's meeting.

We will also review the finer points of how to write your HTML code.
- You should not use `<font>`.
- You have to close your `<img>` tag: `<img src="" />`
- Your events should be functions in your class, read the docs: [Interactivity](http://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html)
