### ISSUE TITLE
Game Screen Right Side - Table Looping

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#74]
Game Screen Right Side

I added a single element, But I am not sure to deal with more then 1.
Sure I can put it in a table. But I dont know how to deal with the looping when putting in data.

I am currently not fully setup. So this is just my current state. Putting here so we have it for the meeting.

Used Setup .jsx as a reference, I think its close. 
1. How to deal with more then 1 row in a table using jsx
2. Does the area above the html section look correct?

Id ask how to test this, but I need to get fully setup in the project first.

[ProgramListItem.zip](https://github.com/gios-asu/dont-get-fired-game/files/126923/ProgramListItem.zip)

**Comment by idmontie** [comment]
Make a pull request after you implement the loop structure I showed you in our meeting:

``` js
(this.props.programs.map((program, i) => (
  <Program program={program} key={i} />
)))
```
