### ISSUE TITLE
commit develop branch

### ISSUE THREAD

**Issue by Tuyenho** [asu-ke-web-services/dont-get-fired-game#78]
i cant push to the develop branch. i got this message said: remote rejected. How do i fix this? 

i'm working on the develop branch. 
![1](https://cloud.githubusercontent.com/assets/8674207/13025862/2333e6c0-d1d0-11e5-99b9-d99a2980b7b2.PNG)

**Comment by idmontie** [comment]
You need to checkout your own branch `git checkout -b tuyenho-develop` and then push to that.

The develop branch is protected.

**Comment by Tuyenho** [comment]
thanks alot this help.
