### ISSUE TITLE
try to commit, showed error

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#79]
<img width="1440" alt="screen shot 2016-02-12 at 23 09 07" src="https://cloud.githubusercontent.com/assets/6620363/13026247/c88c3c82-d1dd-11e5-9466-10ecd2b5a843.png">

**Comment by idmontie** [comment]
That's not an error. Simply select the edit anyway or delete option and make a new commit

**Comment by xyan12345** [comment]
Thanks, got it. i created a new branch, will commit my work tonight
