### ISSUE TITLE
Still Have the old project

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#81]
I tried:
git push
checkout -b new branch 
git commit
git push origin new_branch
However, if i try npm test, it will give errors, and i looked these files. They are old code, and never updated
<img width="1440" alt="screen shot 2016-02-16 at 01 00 25" src="https://cloud.githubusercontent.com/assets/6620363/13070376/449a02ba-d449-11e5-9736-21c7ff1a678d.png">

**Comment by idmontie** [comment]
Have you ran `git pull origin develop`?

**Comment by idmontie** [comment]
At this point, you will most likely have merge conflicts that you will need to resolve as well.

**Comment by xyan12345** [comment]
I just did it, and i do have conflicts on the game. How to resolve the that conflict?

**Comment by xyan12345** [comment]
<img width="1440" alt="screen shot 2016-02-16 at 09 02 10" src="https://cloud.githubusercontent.com/assets/6620363/13082024/31a20a7a-d48c-11e5-93ff-f6561275e598.png">
i had it before. i saw notes on pass issues, you said that we can create a new branch to resolve this problem, it did not help me

**Comment by idmontie** [comment]
Please read up on how to resolve merge conflicts:
https://githowto.com/resolving_conflicts​

**Comment by xyan12345** [comment]
i tried it, I have this message showed up:

//error: Your local changes to the following files would be overwritten by merge:
//.meteor/local/build/.node_version.txt
//Please, commit your changes or stash them before you can merge.

However, i cannot find this file on computer. 

thank you for your help and patient, Ivan!

**Comment by idmontie** [comment]
Make sure to show hidden folders. I think the `.meteor` folder is hidden by default?

**Comment by xyan12345** [comment]
Still have that conflict issue.i tried that command, it can not show which file i should remove or not. When i run meteor, meteor will stop right here. Is that normal? or did i forget to download something in my project? Can i close all of my other branches ?
<img width="1440" alt="screen shot 2016-02-16 at 15 43 14" src="https://cloud.githubusercontent.com/assets/6620363/13093808/7030a692-d4c4-11e5-948b-903282165d29.png">

**Comment by idmontie** [comment]
One meteor says "App running" that means that Meteor has successfully
launched the server. You can go to your web browser to "localhost:3000" and
view it.

If you want to run tests, try "npm test"

**Comment by xyan12345** [comment]
Problem fixed, Thanks Ivan
