### ISSUE TITLE
Difference between shallow and render

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#86]
shallow and render.
I do not understand.

http://airbnb.io/enzyme/docs/api/ShallowWrapper/shallow.html
http://airbnb.io/enzyme/docs/api/ShallowWrapper/render.html

**Comment by idmontie** [comment]
A better description of those functions:

https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md
https://github.com/airbnb/enzyme/blob/master/docs/api/render.md
- Shallow render renders only your component you pass in
- render actually takes your component and renders it to static html
