### ISSUE TITLE
Pulling 85# from Ivan-develop - Issues On My Computer

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#87]
"Please see the following pull request:
https://github.com/gios-asu/dont-get-fired-game/pull/85"

git checkout ivan-develop
git pull ivan-develop

C:\Users\marks\Capstone\dont-get-fired-game>git status
On branch ivan-develop
Your branch is up-to-date with 'origin/ivan-develop'.
nothing to commit, working directory clean

(I can see code and i did review it)

meteor

**Issue #1**: Shows nothing, but it is running, on http://localhost:3000/ (white page, not cant find page)

**npm lint - ran fine**

"C:\Users\marks\Capstone\dont-get-fired-game>npm run lint

> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx"

**npm test**

**Issue #2**
"C:\Users\marks\Capstone\dont-get-fired-game>npm test

> sustainability-game@0.0.1 test C:\Users\marks\Capstone\dont-get-fired-game
> npm run lint && npm run testonly
> 
> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx
> 
> sustainability-game@0.0.1 testonly C:\Users\marks\Capstone\dont-get-fired-game
> mocha $npm_package_options_mocha

C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '$npm_package_options_mocha'
    at Object.lookupFiles (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628:15)
    at C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:325:6)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "testonly"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sustainability-game@0.0.1 testonly: `mocha $npm_package_options_mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sustainability-game@0.0.1 testonly script 'mocha $npm_package_options_mocha'.
npm ERR! This is most likely a problem with the sustainability-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha $npm_package_options_mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls sustainability-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marks\Capstone\dont-get-fired-game\npm-debug.log
npm ERR! Test failed.  See above for more details."
- Reviewed Code, Looks Good (Asked question on it in another issue)
# FULL LOG

C:\Users\marks>cd capstone

C:\Users\marks\Capstone>cd C:\Users\marks\Capstone\dont-get-fired-game

C:\Users\marks\Capstone\dont-get-fired-game>git checkout idmontie
error: pathspec 'idmontie' did not match any file(s) known to git.

C:\Users\marks\Capstone\dont-get-fired-game>git checkout idmontie
error: pathspec 'idmontie' did not match any file(s) known to git.

C:\Users\marks\Capstone\dont-get-fired-game>git checkout ivan-develop
Branch ivan-develop set up to track remote branch ivan-develop from origin.
Switched to a new branch 'ivan-develop'

C:\Users\marks\Capstone\dont-get-fired-game>meteor
[[[[[ C:\Users\marks\Capstone\dont-get-fired-game ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

Terminate batch job (Y/N)?
^C
C:\Users\marks\Capstone\dont-get-fired-game>git pull ivan-develop
fatal: 'ivan-develop' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Users\marks\Capstone\dont-get-fired-game>git pull
remote: Counting objects: 50, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 50 (delta 17), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (50/50), done.
From https://github.com/gios-asu/dont-get-fired-game
   119ebb1..8aee084  ivan-develop -> origin/ivan-develop
Updating 119ebb1..8aee084
Fast-forward
 .meteor/release                                    |   2 +-
 .meteor/versions                                   | 117 +++++++++++----------
 .../game/program-list-item/_program-list-item.scss |  15 +++
 .../game/program-list-item/program-list-item.jsx   |  33 ++++++
 .../program-list-item/tests/program-list-item.jsx  |  17 +++
 .../components/game/program-list/program-list.jsx  |  15 +++
 .../game/program-list/tests/program-list.jsx       |  23 ++++
 client/components/game/program/_program.scss       |  15 +++
 client/components/game/program/program.jsx         |  29 +++++
 client/components/game/program/tests/program.jsx   |  17 +++
 client/components/game/programs/programs.jsx       |  11 ++
 client/index.html                                  |   2 +-
 client/styles/main.scss                            |   2 +
 package.json                                       |   8 +-
 14 files changed, 243 insertions(+), 63 deletions(-)
 create mode 100644 client/components/game/program-list-item/_program-list-item.scss
 create mode 100644 client/components/game/program-list-item/program-list-item.jsx
 create mode 100644 client/components/game/program-list-item/tests/program-list-item.jsx
 create mode 100644 client/components/game/program-list/program-list.jsx
 create mode 100644 client/components/game/program-list/tests/program-list.jsx
 create mode 100644 client/components/game/program/_program.scss
 create mode 100644 client/components/game/program/program.jsx
 create mode 100644 client/components/game/program/tests/program.jsx
 create mode 100644 client/components/game/programs/programs.jsx

C:\Users\marks\Capstone\dont-get-fired-game>meteor
[[[[[ C:\Users\marks\Capstone\dont-get-fired-game ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

Terminate batch job (Y/N)?
^C
C:\Users\marks\Capstone\dont-get-fired-game>git status
On branch ivan-develop
Your branch is up-to-date with 'origin/ivan-develop'.
nothing to commit, working directory clean

C:\Users\marks\Capstone\dont-get-fired-game>git pull
Already up-to-date.

C:\Users\marks\Capstone\dont-get-fired-game>npm run lint

> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx

C:\Users\marks\Capstone\dont-get-fired-game>npm test

> sustainability-game@0.0.1 test C:\Users\marks\Capstone\dont-get-fired-game
> npm run lint && npm run testonly
> 
> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx
> 
> sustainability-game@0.0.1 testonly C:\Users\marks\Capstone\dont-get-fired-game
> mocha $npm_package_options_mocha

C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '$npm_package_options_mocha'
    at Object.lookupFiles (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628:15)
    at C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:325:6)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "testonly"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sustainability-game@0.0.1 testonly: `mocha $npm_package_options_mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sustainability-game@0.0.1 testonly script 'mocha $npm_package_options_mocha'.
npm ERR! This is most likely a problem with the sustainability-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha $npm_package_options_mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls sustainability-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marks\Capstone\dont-get-fired-game\npm-debug.log
npm ERR! Test failed.  See above for more details.

C:\Users\marks\Capstone\dont-get-fired-game>npm run lint

> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx

C:\Users\marks\Capstone\dont-get-fired-game>git status
On branch ivan-develop
Your branch is up-to-date with 'origin/ivan-develop'.
nothing to commit, working directory clean

C:\Users\marks\Capstone\dont-get-fired-game>npm install
npm WARN package.json Dependency 'react-dom' exists in both dependencies and devDependencies, using 'react-dom@0.14.x' from dependencies
npm WARN package.json Dependency 'underscore' exists in both dependencies and devDependencies, using 'underscore@1.8.3' from dependencies

C:\Users\marks\Capstone\dont-get-fired-game>

**Comment by idmontie** [comment]
> Issue #1: Shows nothing, but it is running, on http://localhost:3000/ (white page, not cant find page)

Open up the console in chrome and report any errors you see.

> Issue #2 Error: cannot resolve path (or pattern) '$npm_package_options_mocha'

Most likely a Windows bug. Get Linux [/sarcasm] That one you'll need to research yourself.

**Comment by msdickinson** [comment]
(Updated First Post, With Full Log In case it helps)

"Uncaught TypeError: Cannot read property 'getInitialState' of undefined"
modules.js:20333
http://localhost:3000/packages/modules.js?hash=4b78158bc16057bbeb3313152cf1c61e6e3d99c9

This Line: *if (!_.isFunction(listenable.getInitialState))
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/reflux/src/connect.js                                                                                  //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
var ListenerMethods = require('reflux-core/lib/ListenerMethods'),                                                      // 1
    ListenerMixin = require('./ListenerMixin'),                                                                        // 2
    _ = require('reflux-core/lib/utils');                                                                              // 3
                                                                                                                       // 4
module.exports = function(listenable,key){                                                                             // 5
    return {                                                                                                           // 6
        getInitialState: function(){                                                                                   // 7
            if (!_.isFunction(listenable.getInitialState)) {                                                           // 8
                return {};                                                                                             // 9
            } else if (key === undefined) {                                                                            // 10
                return listenable.getInitialState();                                                                   // 11
            } else {                                                                                                   // 12
                return _.object([key],[listenable.getInitialState()]);                                                 // 13
            }                                                                                                          // 14
        },                                                                                                             // 15
        componentDidMount: function(){                                                                                 // 16
            _.extend(this,ListenerMethods);                                                                            // 17
            var me = this, cb = (key === undefined ? this.setState : function(v){                                      // 18
                if (typeof me.isMounted === "undefined" || me.isMounted() === true) {                                  // 19
                    me.setState(_.object([key],[v]));                                                                  // 20
                }                                                                                                      // 21
            });                                                                                                        // 22
            this.listenTo(listenable,cb);                                                                              // 23
        },                                                                                                             // 24
        componentWillUnmount: ListenerMixin.componentWillUnmount                                                       // 25
    };                                                                                                                 // 26
};

**Comment by idmontie** [comment]
Rerun `npm install` and see if that helps. I think I bumped the version for some meteor and npm stuff.

**Comment by msdickinson** [comment]
Same Error

## LOG

C:\Users\marks\Capstone\dont-get-fired-game>npm install
npm WARN package.json Dependency 'react-dom' exists in both dependencies and devDependencies, using 'react-dom@0.14.x' from dependencies
npm WARN package.json Dependency 'underscore' exists in both dependencies and devDependencies, using 'underscore@1.8.3' from dependencies

C:\Users\marks\Capstone\dont-get-fired-game>meteor
[[[[[ C:\Users\marks\Capstone\dont-get-fired-game ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

**Comment by msdickinson** [comment]
I can delete all files, from my folder and do it from scratch. If you think that will fix it.

**Comment by idmontie** [comment]
Pull down the latest change and see if that works.

**Comment by msdickinson** [comment]
**Issue 1 Resolved (Issue 2 is not see next post i put after this)**

Thanks

C:\Users\marks\Capstone\dont-get-fired-game>git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/gios-asu/dont-get-fired-game
   8aee084..668b734  ivan-develop -> origin/ivan-develop
Updating 8aee084..668b734
Fast-forward
 client/stores/scene-store.jsx | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

C:\Users\marks\Capstone\dont-get-fired-game>meteor
[[[[[ C:\Users\marks\Capstone\dont-get-fired-game ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

![works](https://cloud.githubusercontent.com/assets/2480828/13167066/88bbb7a0-d68c-11e5-9cfd-ccd13e45635f.PNG)

**Comment by msdickinson** [comment]
But Issue # 2 Still exist

C:\Users\marks\Capstone\dont-get-fired-game>git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/gios-asu/dont-get-fired-game
   8aee084..668b734  ivan-develop -> origin/ivan-develop
Updating 8aee084..668b734
Fast-forward
 client/stores/scene-store.jsx | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

C:\Users\marks\Capstone\dont-get-fired-game>meteor
[[[[[ C:\Users\marks\Capstone\dont-get-fired-game ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

Terminate batch job (Y/N)? meteor
^C
C:\Users\marks\Capstone\dont-get-fired-game>npm run lint

> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx

C:\Users\marks\Capstone\dont-get-fired-game>npm test

> sustainability-game@0.0.1 test C:\Users\marks\Capstone\dont-get-fired-game
> npm run lint && npm run testonly
> 
> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx
> 
> sustainability-game@0.0.1 testonly C:\Users\marks\Capstone\dont-get-fired-game
> mocha $npm_package_options_mocha

C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '$npm_package_options_mocha'
    at Object.lookupFiles (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628:15)
    at C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:325:6)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "testonly"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sustainability-game@0.0.1 testonly: `mocha $npm_package_options_mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sustainability-game@0.0.1 testonly script 'mocha $npm_package_options_mocha'.
npm ERR! This is most likely a problem with the sustainability-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha $npm_package_options_mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls sustainability-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marks\Capstone\dont-get-fired-game\npm-debug.log
npm ERR! Test failed.  See above for more details.

C:\Users\marks\Capstone\dont-get-fired-game>

**Comment by idmontie** [comment]
Try changing the line 5 in package.json to `"mocha": "--require .scripts/mocha_runner client/**/tests/**/*.js"`

Then re-run.

If successful, that means that windows will not be able to use bash patterns.

Are you running this from the npm command line?

Lastly, try the following line as well:

`"mocha": "--require .scripts/mocha_runner client/**/tests/**/*.js client/**/tests/**/*.jsx"`

**Comment by msdickinson** [comment]
**Updated File first one**
`"mocha": "--require .scripts/mocha_runner client/**/tests/**/*.js"`

Then ran

C:\Users\marks\Capstone\dont-get-fired-game>npm test

> sustainability-game@0.0.1 test C:\Users\marks\Capstone\dont-get-fired-game
> npm run lint && npm run testonly
> 
> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx
> 
> sustainability-game@0.0.1 testonly C:\Users\marks\Capstone\dont-get-fired-game
> mocha $npm_package_options_mocha

C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '$npm_package_options_mocha'
    at Object.lookupFiles (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628:15)
    at C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:325:6)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "testonly"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sustainability-game@0.0.1 testonly: `mocha $npm_package_options_mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sustainability-game@0.0.1 testonly script 'mocha $npm_package_options_mocha'.
npm ERR! This is most likely a problem with the sustainability-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha $npm_package_options_mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls sustainability-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marks\Capstone\dont-get-fired-game\npm-debug.log
npm ERR! Test failed.  See above for more details.

**Updated with your bottom one**
`"mocha": "--require .scripts/mocha_runner client/**/tests/**/*.js client/**/tests/**/*.jsx"`
and got

C:\Users\marks\Capstone\dont-get-fired-game>npm test

> sustainability-game@0.0.1 test C:\Users\marks\Capstone\dont-get-fired-game
> npm run lint && npm run testonly
> 
> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx
> 
> sustainability-game@0.0.1 testonly C:\Users\marks\Capstone\dont-get-fired-game
> mocha $npm_package_options_mocha

C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '$npm_package_options_mocha'
    at Object.lookupFiles (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\utils.js:628:15)
    at C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:325:6)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "testonly"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sustainability-game@0.0.1 testonly: `mocha $npm_package_options_mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sustainability-game@0.0.1 testonly script 'mocha $npm_package_options_mocha'.
npm ERR! This is most likely a problem with the sustainability-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha $npm_package_options_mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls sustainability-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marks\Capstone\dont-get-fired-game\npm-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by idmontie** [comment]
This seems like a Windows related issue then. You'll have to look into it youself. I can take a look tomorrow on my windows machine at work.

**Comment by msdickinson** [comment]
I Can Ask Tyuen To try it on hes machine to see if its just my machine thats having the issue.

**Comment by msdickinson** [comment]
Sounds good Thanks ill give it a shot.

**Comment by idmontie** [comment]
Are you using the Node Command Line for this? Can you try using the Git command line?

If it doesn't work in Git command line default, try running `$npm_package_options_mocha="--require .scripts/mocha_runner client/**/tests/**/*.js?(x)" npm test`

**Comment by idmontie** [comment]
Alright, I fixed it for you Windows users. Not sure why env vars weren't working, but the bash globs I can understand.
