### ISSUE TITLE
Run Meteor on ivan-develop branch

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#88]
i am able to run it on my branch. However, if i switch to your branch, it is not working and nothing showed up
<img width="1440" alt="screen shot 2016-02-19 at 12 13 05" src="https://cloud.githubusercontent.com/assets/6620363/13188041/39a649de-d70c-11e5-8ef9-c321959d7758.png">
<img width="1440" alt="screen shot 2016-02-19 at 13 25 02" src="https://cloud.githubusercontent.com/assets/6620363/13188043/3b3328e4-d70c-11e5-811b-d397f6b27a5f.png">

**Comment by xyan12345** [comment]
<img width="1440" alt="screen shot 2016-02-19 at 13 28 24" src="https://cloud.githubusercontent.com/assets/6620363/13188118/af684b36-d70c-11e5-9033-d75255b67689.png">

**Comment by idmontie** [comment]
See Mark and my discussion here and see if that solves your issues: https://github.com/gios-asu/dont-get-fired-game/issues/87

**Comment by idmontie** [comment]
First step: make sure to pull the latest version of the branch down

Rerun npm install

Post the console for `localhost:3000`.

**Comment by xyan12345** [comment]
Thx, "git pull" fixed problem!
