### ISSUE TITLE
Undefined variable 

### ISSUE THREAD

**Issue by Tuyenho** [asu-ke-web-services/dont-get-fired-game#89]
i try to write a test case for eventPage.jsx and it show that the 'event' is undefined. How do i fix this error? 

this is eventPage.jsx:
`import React from 'react';
export default React.createClass({
  onClick() {
    //
  },

  render() {
    return (
        <div className="eventPage">
          <h1 className="eventPage_headline_box">{this.props.event.name}</h1>
          <span className="eventPage__information">
            {this.props.event.explaint}
            <br/>
            {this.progs.event.options}
            <button onClick={this.onClick}>option 1</button>
            <button onClick={this.onClick}>option 2</button>
          </span>
        </div>
    );
  }
}); `

this is eventPage.jsx test case: 
`import React from 'react';
import {expect} from 'chai';
import {shallow} from 'enzyme';
const {describe, it} = global;

import { default as Event } from '../eventPage.jsx';

describe('Event Page', () => {
  const event = {
    options: 'Option 1 or Options 2'
  };

  it( 'has options', () => {
    const wrapper = shallow(<Event event={event} />);
    expect(wrapper.contains('production')).to.equal(true);
  });
});
 `
![9](https://cloud.githubusercontent.com/assets/8674207/13213813/c117f4be-d908-11e5-88e0-5d96b692ff6f.JPG)

**Comment by idmontie** [comment]
Use triple ticks (```) to wrap your code so that it its readable.

**Comment by idmontie** [comment]
Also `this.progs.event` should be `this.props.event`.
