### ISSUE TITLE
NewLine error

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#90]
I have a issue with my index file, but i did not do any changes. Does anyone have the same problem
<img width="572" alt="ddd32dc9-3c08-4150-95bb-0a2924e288af" src="https://cloud.githubusercontent.com/assets/6620363/13262909/80f1e058-da24-11e5-84a8-97827614e864.png">

**Comment by idmontie** [comment]
Alright, I fixed this.
