### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by xyan12345** [asu-ke-web-services/dont-get-fired-game#99]
I think we do have a mockup slides on wiki, but i can not find it, and i asked my teammate, they can not find it too. Can you help me with that? I wanna see what the MainSideBar and MainCompanyTitle looks like. 

Thanks,

**Comment by idmontie** [comment]
https://github.com/gios-asu/dont-get-fired-game/wiki/1-29-16-Meeting-Notes

https://docs.google.com/presentation/d/1eXKLyyfiUU9UC9Ez8Qig4V8cLTQBYDR1t9ysQLdQ3No/pub?start=false&loop=false&delayms=3000&slide=id.p

**Comment by xyan12345** [comment]
thx
